spring.application.name=AuthService
spring.threads.virtual.enabled=true
#server.port=8082
#
#
#services.user.url=http://user-service:8080
#
#
#spring.datasource.url=jdbc:postgresql://auth-db:5432/auth_db
#spring.datasource.username=admin
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=update


# ?????????? ??? ????? ?'??????? ?? 50 ?????? (Neon ????? ??? ????? 60)
spring.datasource.hikari.max-lifetime=50000
# ??? ?????????? ?? ?????? (?? ????? ???? ?????? ?????)
spring.datasource.hikari.connection-timeout=20000
# ????????? "?????????" ??????? ????? 30 ???
spring.datasource.hikari.keepalive-time=30000



#application.security.jwt.secret-key=btBj7JTPQAqws4VNmPlIBDVL32AxRxUSxy9DhvL548U=
##5 min
#application.security.jwt.access-token.expiration=300000
##60 days
#application.security.jwt.refresh-token.expiration=604800000

# ???????? ???? ?? ????????????? (Docker ???? ?????????????)
server.port=8082
grpc.client.user-service.address=${GRPC_CLIENT_USER_SERVICE_ADDRESS:user-service:9090}
grpc.client.user-service.negotiationType=plaintext
# ????????????? ??????? DEBUG ??? ?????? gRPC
#logging.level.io.grpc=DEBUG

# ????????????? ??????? DEBUG ??? Spring Boot gRPC Starter (????? ???????)
logging.level.net.devh=DEBUG

# --- ???????????? ?? (???????? ? environment) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/auth_db?TimeZone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# --- ???????????? Feign ??????? (???????? ? environment) ---
services.user.url=${SERVICES_USER_URL:http://localhost:8081}
logging.level.org.apache.kafka=ERROR
logging.level.org.apache.zookeeper=ERROR

# --- ???????????? JWT (???????? ? environment) ---
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:default_secret_key_for_local_tests}
application.security.jwt.access-token.expiration=${APPLICATION_SECURITY_JWT_ACCESS_TOKEN_EXPIRATION:900000}
application.security.jwt.refresh-token.expiration=${APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:604800000}
#470489649884-bq9rd9mimhk7v0ftd5kgjqs8s4v7stgn.apps.googleusercontent.com  secretID
#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 Client secret