spring.application.name=notification-service
logging.level.org.apache.kafka=ERROR
logging.level.org.apache.zookeeper=ERROR
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
