server:
  port: 8084

webpush:
  vapid:
    public-key: "BAt0Yv_lmLmO723wlUop8HbNakGnUDOjrxHlJhUi5rZgiEdYEnrXEB9cu-mnpCeuobBfRGGBrcwPWVeowH2ZjVs"
    private-key: "ZsPSlvNyUz8B-mmykTnmBlOBCrX1RwgbJIEe745eYw4"
    subject: "mailto:evgeniykompaniec2006@gmail.com" # Це вимога стандарту (контакт адміна)

spring:
  jpa:
    hibernate:
      ddl-auto: update  # 🔥 ОСЬ ЦЕЙ РЯДОК ГОЛОВНИЙ! Він створить таблицю.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${da} # Будемо передавати через Docker/Env
#    password: ${Gd} # Це має бути "App Password", а не звичайний пароль!
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  datasource:
    hikari:
      # Повинно бути менше, ніж таймаут на Neon (зазвичай 30-60 сек)
      max-lifetime: 60000
      # Час очікування вільного з'єднання
      connection-timeout: 20000
      # Перевірка з'єднання перед використанням
      validation-timeout: 3000
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:29092 # Адреса всередині докера
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
