server:
  port: 8084

webpush:
  vapid:
    public-key: "BAt0Yv_lmLmO723wlUop8HbNakGnUDOjrxHlJhUi5rZgiEdYEnrXEB9cu-mnpCeuobBfRGGBrcwPWVeowH2ZjVs"
    private-key: "ZsPSlvNyUz8B-mmykTnmBlOBCrX1RwgbJIEe745eYw4"
    subject: "mailto:evgeniykompaniec2006@gmail.com" # Це вимога стандарту (контакт адміна)

spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${da} # Будемо передавати через Docker/Env
#    password: ${Gd} # Це має бути "App Password", а не звичайний пароль!
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  datasource:
    hikari:
      # Повинно бути менше, ніж таймаут на Neon (зазвичай 30-60 сек)
      max-lifetime: 60000
      # Час очікування вільного з'єднання
      connection-timeout: 20000
      # Перевірка з'єднання перед використанням
      validation-timeout: 3000
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:29092 # Адреса всередині докера
    consumer:
      group-id: notification-group # ID групи (важливо!)
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Ми будемо передавати JSON, тому використовуємо JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: gaiden.da.notificationservice.dto.UserRegisteredEvent
        spring.json.trusted.packages: "*" # Довіряємо всім пакетам DTO