CREATE TABLE contacts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id         VARCHAR(255)                            NOT NULL,
    peer_id          VARCHAR(255)                            NOT NULL,
    last_interaction TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

ALTER TABLE contacts
    ADD CONSTRAINT uc_a909a94118d4a47b065e13ceb UNIQUE (owner_id, peer_id);