-- 1. Створення таблиці контактів (безпечно)
CREATE TABLE IF NOT EXISTS contacts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id         VARCHAR(255)                            NOT NULL,
    peer_id          VARCHAR(255)                            NOT NULL,
    last_interaction TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

-- 2. Створення таблиці повідомлень (безпечно)
CREATE TABLE IF NOT EXISTS messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content      TEXT,
    sender       VARCHAR(255),
    guild_id     VARCHAR(255),
    channel_id   VARCHAR(255),
    recipient_id VARCHAR(255),
    timestamp    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

-- 3. Додавання унікального констрейнту (БЕЗПЕЧНО ЧЕРЕЗ ПЕРЕВІРКУ)
DO $$
    BEGIN
        -- Перевіряємо, чи існує вже такий констрейнт
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'uc_a909a94118d4a47b065e13ceb'
        ) THEN
            -- Якщо не існує, додаємо його
            ALTER TABLE contacts
                ADD CONSTRAINT uc_a909a94118d4a47b065e13ceb UNIQUE (owner_id, peer_id);
        END IF;
    END $$;