-- 1. Создаем основную таблицу пользователей
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(255) NOT NULL UNIQUE, -- Уникальное имя (как в @Column)
                                     email VARCHAR(255) NOT NULL,           -- Email обязателен
                                     password VARCHAR(255) NOT NULL,
                                     created_at TIMESTAMP,
                                     updated_at TIMESTAMP
);


CREATE TABLE IF NOT EXISTS user_owned_guilds (
                                                 user_id BIGINT NOT NULL,
                                                 guild_id BIGINT,
                                                 CONSTRAINT fk_user_owned_guilds_users FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);