
server.port=8083
spring.application.name=guild-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/guild_db?TimeZone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.max-lifetime=50000

spring.datasource.hikari.connection-timeout=20000

spring.datasource.hikari.keepalive-time=30000


spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

grpc.server.port=${GRPC_SERVER_PORT:9093}

grpc.server.security.enabled=${GRPC_SERVER_SECURITY_ENABLED:false}

grpc.client.user-service.address=${GRPC_CLIENT_USER_SERVICE_ADDRESS:static://localhost:9090}
grpc.client.user-service.negotiationType=${GRPC_CLIENT_USER_SERVICE_NEGOTIATION_TYPE:plaintext}