spring.application.name=chat-service
SPRING_FLYWAY_ENABLED=true
logging.level.org.apache.kafka=ERROR
logging.level.org.apache.zookeeper=ERROR
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.max-lifetime=50000

spring.datasource.hikari.connection-timeout=20000

spring.datasource.hikari.keepalive-time=30000
aws.s3.bucket=${AWS_S3_BUCKET}

